version: "3.8"

services:
  api:
    container_name: api 
    build: ./api
    environment:
      HTTP_PORT: :8080
      LOG_LEVEL: debug
    depends_on:
      - database
    ports:
      - "8080:8080"

  database:
    container_name: database
    image: postgres:14.1
    environment:
        POSTGRES_DATABASE: newpro
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 123
    expose:
      - "5434" 
    ports:
      - "5432:5432" 
    volumes:
      - dbdata:/var/lib/postgresql/data
    command: -p 5434

  migrate:
    image: migrate/migrate
    # networks:
    #   - new
    volumes:
      - ./migrations:/migrations
    command:
       ["-path", "/migrations", "-database",  "postgres://coder:123@database:5434/newpro?sslmode=disable", "up"]
    links:
     - database

volumes:
  dbdata: # create the volume for persisting data.